const puppeteer=require('puppeteer-core');const http=require('http');const path=require('path');const fs=require('fs');
const CHROME='C:/Program Files/Google/Chrome/Application/chrome.exe';const ROOT=path.resolve(__dirname,'..');const PORT=4925;const BASE=`http://127.0.0.1:${PORT}`;
const MIME={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.svg':'image/svg+xml'};
const ZCODE='zztestinternalsafeto',ZPW='ZzTest!2026',KBH='3249e3b5-c411-4f5f-ae48-0246304c9c87';const sleep=ms=>new Promise(r=>setTimeout(r,ms));const OUT=path.join(__dirname,'or_shots');
function serve(){return new Promise(res=>{const s=http.createServer((q,p)=>{let f=path.join(ROOT,decodeURIComponent(q.url.split('?')[0])==='/'?'login.html':decodeURIComponent(q.url.split('?')[0]));if(!fs.existsSync(f)||fs.statSync(f).isDirectory()){p.writeHead(404);return p.end();}p.writeHead(200,{'Content-Type':MIME[path.extname(f)]||'text/plain'});fs.createReadStream(f).pipe(p);}).listen(PORT,'127.0.0.1',()=>res(s));});}
(async()=>{fs.mkdirSync(OUT,{recursive:true});const srv=await serve();const b=await puppeteer.launch({executablePath:CHROME,headless:'new',args:['--no-sandbox','--window-size=1600,1100']});
const errs=[];const p=await b.newPage();await p.setViewport({width:1560,height:1040});
p.on('pageerror',e=>errs.push(e.message));p.on('console',m=>{if(m.type()==='error'&&!/403|favicon/.test(m.text()))errs.push(m.text());});
await p.goto(BASE+'/login.html',{waitUntil:'networkidle2'});await sleep(900);
await p.evaluate((c,q)=>{const u=document.getElementById('li-u'),w=document.getElementById('li-p');u.removeAttribute('readonly');w.removeAttribute('readonly');u.value=c;w.value=q;window._loginReadyAt=0;},ZCODE,ZPW);
await p.evaluate(()=>doLogin());await sleep(6500);
await p.evaluate(()=>{document.getElementById('s-onboarding')?.classList.remove('on');});
await p.evaluate((kbh)=>{ S.cid=kbh; }, KBH);
await p.evaluate(()=>{ if(typeof rMyRecovery==='function') rMyRecovery(); });
await sleep(5000);
await p.evaluate(()=>{ document.querySelectorAll('.pg').forEach(x=>x.classList.remove('on')); document.getElementById('pg-myrecovery')?.classList.add('on'); });
await p.screenshot({path:path.join(OUT,"tools_table.png")});
const funcs=await p.evaluate(()=>({openConModal:typeof openConModal,escOpenNew:typeof escOpenNew}));
const btns=//skip#or-table tbody tr'); if(!tr) return null; var cell=tr.querySelector('td:last-child'); return cell?cell.querySelectorAll('a,button').length:0; });
const titles=//skip#or-table tbody tr'); if(!tr) return []; return [...tr.querySelector('td:last-child').querySelectorAll('a,button')].map(x=>x.getAttribute('title')); });
await p.screenshot({path:path.join(OUT,"tools_table.png"),fullPage:false});
//skip#or-table tbody tr'); var btns=tr.querySelector('td:last-child').querySelectorAll('a,button'); var pr=[...btns].find(x=>/promise/i.test(x.getAttribute('title')||'')); if(pr) pr.click(); });
await sleep(1500);
const promiseModalOpen=await p.evaluate(()=>{ var m=document.getElementById('m-con'); return !!m && getComputedStyle(m).display!=='none'; });
await p.screenshot({path:path.join(OUT,'tools_promise.png'),fullPage:false});
// close & click Escalate
await p.evaluate(()=>{ if(typeof cm==='function')cm('m-con'); document.querySelectorAll('.nx-modal-overlay,.mov').forEach(x=>{try{x.remove()}catch(e){}}); });
await sleep(600);
//skip#or-table tbody tr'); var btns=tr.querySelector('td:last-child').querySelectorAll('a,button'); var es=[...btns].find(x=>/escalate/i.test(x.getAttribute('title')||'')); if(es) es.click(); });
await sleep(1800);
const escModalOpen=await p.evaluate(()=>{ var m=document.getElementById('m-esc-new'); return !!m && getComputedStyle(m).display!=='none'; });
await b.close();srv.close();
console.log('funcs:',JSON.stringify(funcs));
console.log('action buttons per row:',btns,'(want 5)');
console.log('titles:',JSON.stringify(titles));
console.log('Promise click -> con modal open:',promiseModalOpen);
console.log('Escalate click -> escalation modal open:',escModalOpen);
console.log('errors:',errs.length);errs.slice(0,6).forEach(e=>console.log('  '+e));
})().catch(e=>{console.error(e);process.exit(1)});
