-- ═══════════════════════════════════════════════════════════════════════════
-- Awami Market · Fifth Floor, revised plan (AWAMI MARKIT.pdf, 25 Sep 2026)
-- Generated by make_sql.js on 2026-09-29; nothing in the VALUES list was typed.
--
-- 136 old units (5F-01 .. 5F-136, one-room "UNIT"s) become 97 flats (5F-501 .. 5F-597):
--   * 97 old rows are KEPT and renamed (their id survives, so 5F-01's two
--     cancelled reservations and its request stay attached to 5F-501);
--   * 39 old rows that were merged into a neighbour are DELETED — none has a
--     sale, token, active booking, lead, quote, transfer or any other reference.
-- area   : the PDF's AREA= label; 523/524/566 keep their old area (878.00 / 575.20 /
--          578.79) on the owner's word — the PDF's 478.25 / 475.20 / 678.80 disagree
--          with the rooms drawn on the same sheet.
-- price  : area x 11,000 (the floor's current rate, unchanged).
-- type   : read off the drawing (Studio 9, 1 Bed 49, 2 Bed 34, 3 Bed 5).
-- Totals after: 97 units, 73395.27 sq ft, PKR 807347970.00.
-- The block refuses to run unless the floor is exactly as it was checked: 136 units,
-- all Available, nothing sold, nothing actively held.
-- ═══════════════════════════════════════════════════════════════════════════

DO $mig$
DECLARE
  v_pr constant uuid := '59ded55b-9bc2-45b2-a372-49fc31807fa9';
  v_n int; v_bad int; v_area numeric; v_price numeric; v_missing int;
BEGIN
  /* ── the floor must be exactly what was checked ── */
  SELECT count(*) INTO v_n FROM public.units WHERE project_id = v_pr AND floor_label = 'Fifth Floor';
  IF v_n <> 136 THEN RAISE EXCEPTION 'expected 136 Fifth Floor units, found %', v_n; END IF;
  SELECT count(*) INTO v_bad FROM public.units u
    LEFT JOIN public.category_unit_statuses cs ON cs.id = u.status_id
   WHERE u.project_id = v_pr AND u.floor_label = 'Fifth Floor' AND NOT COALESCE(cs.is_available, false);
  IF v_bad > 0 THEN RAISE EXCEPTION '% Fifth Floor units are no longer Available — stop and re-check', v_bad; END IF;
  SELECT count(*) INTO v_bad FROM public.reservations r JOIN public.units u ON u.id = r.unit_id
   WHERE u.project_id = v_pr AND u.floor_label = 'Fifth Floor' AND r.status = 'active';
  IF v_bad > 0 THEN RAISE EXCEPTION '% active reservations on the Fifth Floor — stop', v_bad; END IF;
  SELECT count(*) INTO v_bad FROM public.sales s JOIN public.units u ON u.id = s.unit_id
   WHERE u.project_id = v_pr AND u.floor_label = 'Fifth Floor';
  IF v_bad > 0 THEN RAISE EXCEPTION '% sales on the Fifth Floor — stop', v_bad; END IF;

  CREATE TEMP TABLE _f5 (keep text, new_no text, area numeric, price numeric, type_name text) ON COMMIT DROP;
  INSERT INTO _f5 VALUES
    ('5F-01', '5F-501', 569.50, 6264500.00, '1 Bed Apartment'),
    ('5F-02', '5F-502', 556.20, 6118200.00, '1 Bed Apartment'),
    ('5F-03', '5F-503', 554.00, 6094000.00, '1 Bed Apartment'),
    ('5F-04', '5F-504', 552.00, 6072000.00, '1 Bed Apartment'),
    ('5F-05', '5F-505', 550.00, 6050000.00, '1 Bed Apartment'),
    ('5F-06', '5F-506', 546.00, 6006000.00, 'Studio Apartment'),
    ('5F-07', '5F-507', 539.85, 5938350.00, 'Studio Apartment'),
    ('5F-08', '5F-508', 533.60, 5869600.00, 'Studio Apartment'),
    ('5F-09', '5F-509', 520.15, 5721650.00, 'Studio Apartment'),
    ('5F-10', '5F-510', 516.75, 5684250.00, 'Studio Apartment'),
    ('5F-11', '5F-511', 495.50, 5450500.00, 'Studio Apartment'),
    ('5F-12', '5F-512', 490.00, 5390000.00, 'Studio Apartment'),
    ('5F-13', '5F-513', 499.25, 5491750.00, 'Studio Apartment'),
    ('5F-14', '5F-514', 748.23, 8230530.00, '1 Bed Apartment'),
    ('5F-15', '5F-515', 730.00, 8030000.00, '1 Bed Apartment'),
    ('5F-16', '5F-516', 733.50, 8068500.00, '1 Bed Apartment'),
    ('5F-17', '5F-517', 736.50, 8101500.00, '1 Bed Apartment'),
    ('5F-18', '5F-518', 737.60, 8113600.00, '1 Bed Apartment'),
    ('5F-19', '5F-519', 738.50, 8123500.00, '1 Bed Apartment'),
    ('5F-20', '5F-520', 739.40, 8133400.00, '1 Bed Apartment'),
    ('5F-21', '5F-521', 740.00, 8140000.00, '1 Bed Apartment'),
    ('5F-22', '5F-522', 740.50, 8145500.00, '1 Bed Apartment'),
    ('5F-23', '5F-523', 878.00, 9658000.00, '1 Bed Apartment'),
    ('5F-24', '5F-524', 575.20, 6327200.00, '1 Bed Apartment'),
    ('5F-25', '5F-525', 1222.80, 13450800.00, '3 Bed Apartment'),
    ('5F-27', '5F-526', 1336.15, 14697650.00, '3 Bed Apartment'),
    ('5F-29', '5F-527', 1431.00, 15741000.00, '3 Bed Apartment'),
    ('5F-31', '5F-528', 1439.00, 15829000.00, '3 Bed Apartment'),
    ('5F-33', '5F-529', 1394.30, 15337300.00, '3 Bed Apartment'),
    ('5F-67', '5F-530', 897.00, 9867000.00, '2 Bed Apartment'),
    ('5F-65', '5F-531', 885.00, 9735000.00, '2 Bed Apartment'),
    ('5F-63', '5F-532', 885.00, 9735000.00, '2 Bed Apartment'),
    ('5F-61', '5F-533', 885.00, 9735000.00, '2 Bed Apartment'),
    ('5F-59', '5F-534', 885.00, 9735000.00, '2 Bed Apartment'),
    ('5F-58', '5F-535', 909.50, 10004500.00, '2 Bed Apartment'),
    ('5F-56', '5F-536', 972.80, 10700800.00, '2 Bed Apartment'),
    ('5F-54', '5F-537', 891.00, 9801000.00, '2 Bed Apartment'),
    ('5F-52', '5F-538', 891.00, 9801000.00, '2 Bed Apartment'),
    ('5F-50', '5F-539', 891.00, 9801000.00, '2 Bed Apartment'),
    ('5F-48', '5F-540', 903.00, 9933000.00, '2 Bed Apartment'),
    ('5F-47', '5F-541', 838.00, 9218000.00, '2 Bed Apartment'),
    ('5F-45', '5F-542', 843.00, 9273000.00, '2 Bed Apartment'),
    ('5F-43', '5F-543', 843.00, 9273000.00, '2 Bed Apartment'),
    ('5F-41', '5F-544', 885.30, 9738300.00, '2 Bed Apartment'),
    ('5F-39', '5F-545', 885.50, 9740500.00, '2 Bed Apartment'),
    ('5F-37', '5F-546', 889.35, 9782850.00, '2 Bed Apartment'),
    ('5F-35', '5F-547', 1017.20, 11189200.00, '2 Bed Apartment'),
    ('5F-69', '5F-548', 984.20, 10826200.00, '2 Bed Apartment'),
    ('5F-71', '5F-549', 878.00, 9658000.00, '2 Bed Apartment'),
    ('5F-73', '5F-550', 885.00, 9735000.00, '2 Bed Apartment'),
    ('5F-75', '5F-551', 885.70, 9742700.00, '2 Bed Apartment'),
    ('5F-77', '5F-552', 843.50, 9278500.00, '2 Bed Apartment'),
    ('5F-79', '5F-553', 843.50, 9278500.00, '2 Bed Apartment'),
    ('5F-82', '5F-554', 903.50, 9938500.00, '2 Bed Apartment'),
    ('5F-84', '5F-555', 891.00, 9801000.00, '2 Bed Apartment'),
    ('5F-86', '5F-556', 891.00, 9801000.00, '2 Bed Apartment'),
    ('5F-88', '5F-557', 891.00, 9801000.00, '2 Bed Apartment'),
    ('5F-90', '5F-558', 974.50, 10719500.00, '2 Bed Apartment'),
    ('5F-93', '5F-559', 885.00, 9735000.00, '2 Bed Apartment'),
    ('5F-95', '5F-560', 885.00, 9735000.00, '2 Bed Apartment'),
    ('5F-97', '5F-561', 885.00, 9735000.00, '2 Bed Apartment'),
    ('5F-99', '5F-562', 885.00, 9735000.00, '2 Bed Apartment'),
    ('5F-101', '5F-563', 897.00, 9867000.00, '2 Bed Apartment'),
    ('5F-136', '5F-564', 563.75, 6201250.00, 'Studio Apartment'),
    ('5F-135', '5F-565', 581.80, 6399800.00, '1 Bed Apartment'),
    ('5F-134', '5F-566', 578.79, 6366690.00, '1 Bed Apartment'),
    ('5F-133', '5F-567', 571.50, 6286500.00, '1 Bed Apartment'),
    ('5F-132', '5F-568', 573.75, 6311250.00, '1 Bed Apartment'),
    ('5F-131', '5F-569', 585.80, 6443800.00, '1 Bed Apartment'),
    ('5F-130', '5F-570', 589.45, 6483950.00, '1 Bed Apartment'),
    ('5F-129', '5F-571', 596.35, 6559850.00, '1 Bed Apartment'),
    ('5F-128', '5F-572', 602.00, 6622000.00, '1 Bed Apartment'),
    ('5F-127', '5F-573', 607.00, 6677000.00, '1 Bed Apartment'),
    ('5F-126', '5F-574', 629.50, 6924500.00, '1 Bed Apartment'),
    ('5F-125', '5F-575', 740.25, 8142750.00, '1 Bed Apartment'),
    ('5F-124', '5F-576', 627.00, 6897000.00, '1 Bed Apartment'),
    ('5F-123', '5F-577', 625.30, 6878300.00, '1 Bed Apartment'),
    ('5F-122', '5F-578', 621.50, 6836500.00, '1 Bed Apartment'),
    ('5F-121', '5F-579', 621.70, 6838700.00, '1 Bed Apartment'),
    ('5F-120', '5F-580', 627.50, 6902500.00, '1 Bed Apartment'),
    ('5F-119', '5F-581', 629.00, 6919000.00, '1 Bed Apartment'),
    ('5F-118', '5F-582', 627.90, 6906900.00, '1 Bed Apartment'),
    ('5F-117', '5F-583', 626.50, 6891500.00, '1 Bed Apartment'),
    ('5F-116', '5F-584', 649.35, 7142850.00, '1 Bed Apartment'),
    ('5F-115', '5F-585', 649.60, 7145600.00, '1 Bed Apartment'),
    ('5F-114', '5F-586', 664.60, 7310600.00, '1 Bed Apartment'),
    ('5F-113', '5F-587', 674.00, 7414000.00, '1 Bed Apartment'),
    ('5F-112', '5F-588', 665.70, 7322700.00, '1 Bed Apartment'),
    ('5F-111', '5F-589', 654.80, 7202800.00, '1 Bed Apartment'),
    ('5F-110', '5F-590', 644.00, 7084000.00, '1 Bed Apartment'),
    ('5F-109', '5F-591', 633.15, 6964650.00, '1 Bed Apartment'),
    ('5F-108', '5F-592', 622.30, 6845300.00, '1 Bed Apartment'),
    ('5F-107', '5F-593', 611.35, 6724850.00, '1 Bed Apartment'),
    ('5F-106', '5F-594', 600.15, 6601650.00, '1 Bed Apartment'),
    ('5F-105', '5F-595', 588.90, 6477900.00, '1 Bed Apartment'),
    ('5F-104', '5F-596', 577.80, 6355800.00, '1 Bed Apartment'),
    ('5F-103', '5F-597', 685.20, 7537200.00, '1 Bed Apartment');

  SELECT count(*) INTO v_missing FROM _f5 f
   WHERE NOT EXISTS (SELECT 1 FROM public.units u WHERE u.project_id = v_pr AND u.unit_no = f.keep)
      OR NOT EXISTS (SELECT 1 FROM public.category_unit_types t WHERE t.project_id = v_pr AND t.type_name = f.type_name);
  IF v_missing > 0 THEN RAISE EXCEPTION '% rows refer to a unit or type that is not there', v_missing; END IF;

  /* ── the 39 merged-away rows go first, so no rename can collide ── */
  DELETE FROM public.units u
   WHERE u.project_id = v_pr AND u.floor_label = 'Fifth Floor'
     AND u.unit_no NOT IN (SELECT keep FROM _f5);
  GET DIAGNOSTICS v_n = ROW_COUNT;
  IF v_n <> 39 THEN RAISE EXCEPTION 'deleted % rows, expected 39', v_n; END IF;

  /* ── the 97 kept rows become the new flats ── */
  UPDATE public.units u
     SET unit_no = f.new_no, unit_code = f.new_no, area = f.area, base_price = f.price,
         unit_type_id = (SELECT t.id FROM public.category_unit_types t
                          WHERE t.project_id = v_pr AND t.type_name = f.type_name)
    FROM _f5 f
   WHERE u.project_id = v_pr AND u.unit_no = f.keep;
  GET DIAGNOSTICS v_n = ROW_COUNT;
  IF v_n <> 97 THEN RAISE EXCEPTION 'updated % rows, expected 97', v_n; END IF;

  /* ── and the floor adds up ── */
  SELECT count(*), sum(area), sum(base_price) INTO v_n, v_area, v_price
    FROM public.units WHERE project_id = v_pr AND floor_label = 'Fifth Floor';
  IF v_n <> 97 OR v_area <> 73395.27 OR v_price <> 807347970.00 THEN
    RAISE EXCEPTION 'after: % units, % sq ft, % PKR — not the expected 97 / 73395.27 / 807347970.00', v_n, v_area, v_price;
  END IF;
END $mig$;
