const puppeteer=require('puppeteer-core');const http=require('http');const path=require('path');const fs=require('fs');
const ROOT=path.resolve(__dirname,'..');const PORT=4739;const BASE=`http://127.0.0.1:${PORT}`;
const CHROME='C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
const MIME={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.svg':'image/svg+xml','.json':'application/json','.woff2':'font/woff2','.ico':'image/x-icon'};
function serve(){return new Promise(res=>{const srv=http.createServer((q,p)=>{const u=decodeURIComponent(q.url.split('?')[0]);let f=path.join(ROOT,u==='/'?'login.html':u);if(!f.startsWith(ROOT)||!fs.existsSync(f)||fs.statSync(f).isDirectory()){p.writeHead(404);return p.end();}p.writeHead(200,{'Content-Type':MIME[path.extname(f)]||'application/octet-stream'});fs.createReadStream(f).pipe(p);}).listen(PORT,'127.0.0.1',()=>res(srv));});}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{const srv=await serve();
  const b=await puppeteer.launch({executablePath:CHROME,headless:'new',args:['--no-sandbox','--window-size=1100,1200']});
  const page=await b.newPage();await page.setViewport({width:1050,height:1150});
  page.on('dialog',async d=>{try{await d.accept();}catch(e){}});
  await page.goto(BASE+'/login.html',{waitUntil:'networkidle2'});await sleep(900);
  await page.evaluate(()=>{const u=document.getElementById('li-u'),q=document.getElementById('li-p');u.removeAttribute('readonly');q.removeAttribute('readonly');u.value='awami';q.value='Samsungnote123*';window._loginReadyAt=0;});
  await page.evaluate(()=>doLogin());await sleep(7000);
  await page.evaluate(()=>{var o=document.getElementById('s-onboarding');if(o)o.classList.remove('on');nav('units');});await sleep(3000);
  await page.evaluate(()=>{if(typeof openUnitModal==='function')openUnitModal(null);});await sleep(1200);
  await page.evaluate(()=>{if(typeof _uToggleMore==='function')_uToggleMore();});await sleep(600);
  const ids=['uf-no','uf-project','uf-floor','uf-block','uf-type','uf-status','uf-area','uf-area-unit','uf-price','uf-carpet','uf-bedrooms','uf-bathrooms','uf-parking','uf-facing','uf-maint','uf-possession','uf-handover','uf-premium','uf-corner','uf-notes'];
  const present=await page.evaluate((ids)=>ids.filter(id=>document.getElementById(id)).length+'/'+ids.length,ids);
  console.log('UNIT FORM FIELDS:',present);
  await page.screenshot({path:path.join(__dirname,'unitform.png'),fullPage:true});
  await b.close();srv.close();
})().catch(e=>{console.error(e.message);process.exit(1);});
