-- ═══════════════════════════════════════════════════════════════════════════
-- NexuFinance double-entry foundation · 2026-09-19h · IIF export-state
-- tracking (Part 1 of 3)
--
-- NOT YET APPLIED — awaiting explicit go-ahead. This is NOT covered by the
-- read-only-additive auto-apply carve-out (docs/PLAN.md §18): it adds a
-- column to the live nf_vouchers table AND backfills all 64 real existing
-- rows. Per the owner's own instruction, IIF export work gets the same
-- treatment as the original history import — dry run, checksum, nothing
-- applied without an explicit go.
--
-- WHY THIS EXISTS, FIRST: the 64 historical vouchers already exist in
-- QuickBooks — that is where they were imported FROM. If a first IIF
-- export ever included them, it would double-post the client's entire
-- history into QuickBooks, and the cleanup is 64 manual deletions there.
-- Every voucher needs an export-eligibility state, checked once and
-- backfilled, not left to convention or narration-text matching.
--
-- SCHEMA
--   nf_vouchers.iif_exportable boolean NOT NULL DEFAULT true — new
--   vouchers (created after this migration, i.e. everything posted
--   through the live app from here on) default to exportable. The
--   one-time backfill below sets this to FALSE for all 64 real imported
--   vouchers, identified by created_by = the system import user
--   (50e3d1be-ef2f-421c-a0f9-2fd2296176e4) — confirmed directly before
--   writing this backfill, not assumed: every one of Awami's 64 real
--   vouchers today shares that exact created_by, and no other voucher
--   exists yet for this company.
--
--   nf_iif_batches — one row per export run: file name, date range, and
--   which QuickBooks chart file/checksum the pre-export validation (Part
--   2, not built here) checked account names against, for audit trail.
--
--   nf_iif_batch_vouchers — which vouchers went into which batch. A
--   voucher with any row here has already been exported once; including
--   it in a later batch requires is_reexport=true AND a non-null reason,
--   enforced by a CHECK constraint, not just application-layer discipline.
--
-- RPCs
--   nf_iif_list_candidates(company, from, to) — the default candidate
--   set for a new export: POSTED vouchers in range, iif_exportable=true,
--   with no prior nf_iif_batch_vouchers row at all (never exported).
--   Read-only.
--
--   nf_iif_record_batch(company, file_name, from, to, qb_chart_file,
--   qb_chart_checksum, voucher_ids, reexports) — the only write path.
--   Rejects the whole batch (raises, writes nothing) if any voucher_id:
--     is not POSTED, or not iif_exportable, or not in this company; or
--     has a prior export and is not listed in `reexports` with a reason.
--   This RPC records that an export HAPPENED — it does not write the
--   .iif file itself or touch QuickBooks; the file is generated by a
--   script (Part 2) that calls this only after its own validation gate
--   passes, and the owner's explicit go for the resulting file.
-- ═══════════════════════════════════════════════════════════════════════════

BEGIN;

ALTER TABLE public.nf_vouchers ADD COLUMN iif_exportable boolean NOT NULL DEFAULT true;

-- One-time backfill: every real imported voucher is already in
-- QuickBooks and must never be exported back into it.
UPDATE public.nf_vouchers
   SET iif_exportable = false
 WHERE created_by = '50e3d1be-ef2f-421c-a0f9-2fd2296176e4'::uuid;

CREATE TABLE public.nf_iif_batches (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES public.companies(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid NOT NULL,
  file_name text NOT NULL,
  date_from date,
  date_to date,
  qb_chart_file text,
  qb_chart_checksum text
);

CREATE TABLE public.nf_iif_batch_vouchers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  batch_id uuid NOT NULL REFERENCES public.nf_iif_batches(id),
  voucher_id uuid NOT NULL REFERENCES public.nf_vouchers(id),
  company_id uuid NOT NULL REFERENCES public.companies(id),
  exported_at timestamptz NOT NULL DEFAULT now(),
  is_reexport boolean NOT NULL DEFAULT false,
  reason text,
  CONSTRAINT nf_iif_batch_vouchers_reason_ck CHECK (NOT is_reexport OR reason IS NOT NULL)
);
CREATE INDEX nf_iif_batch_vouchers_voucher_idx ON public.nf_iif_batch_vouchers(voucher_id);
CREATE INDEX nf_iif_batch_vouchers_batch_idx ON public.nf_iif_batch_vouchers(batch_id);

CREATE OR REPLACE FUNCTION public.nf_iif_list_candidates(p_company_id uuid, p_from date, p_to date)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE v_out jsonb;
BEGIN
  PERFORM public.nf_require_role(p_company_id, ARRAY['accountant','director']);

  SELECT COALESCE(jsonb_agg(jsonb_build_object(
           'id', v.id, 'voucher_no', v.voucher_no, 'voucher_date', v.voucher_date, 'narration', v.narration)
           ORDER BY v.voucher_date, v.sort), '[]'::jsonb)
    INTO v_out
    FROM public.nf_vouchers v
   WHERE v.company_id = p_company_id AND v.status = 'POSTED' AND v.iif_exportable
     AND (p_from IS NULL OR v.voucher_date >= p_from) AND (p_to IS NULL OR v.voucher_date <= p_to)
     AND NOT EXISTS (SELECT 1 FROM public.nf_iif_batch_vouchers bv WHERE bv.voucher_id = v.id);
  RETURN v_out;
END
$function$;

REVOKE ALL ON FUNCTION public.nf_iif_list_candidates(uuid, date, date) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.nf_iif_list_candidates(uuid, date, date) FROM anon;
GRANT EXECUTE ON FUNCTION public.nf_iif_list_candidates(uuid, date, date) TO authenticated;

CREATE OR REPLACE FUNCTION public.nf_iif_record_batch(
  p_company_id uuid, p_file_name text, p_from date, p_to date,
  p_qb_chart_file text, p_qb_chart_checksum text,
  p_voucher_ids uuid[], p_reexports jsonb DEFAULT '[]'::jsonb
)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid uuid := auth.uid();
  v_batch_id uuid;
  v_id uuid;
  v_reason text;
  v_already_exported uuid[];
BEGIN
  PERFORM public.nf_require_role(p_company_id, ARRAY['accountant','director']);
  IF p_voucher_ids IS NULL OR array_length(p_voucher_ids, 1) IS NULL THEN
    RAISE EXCEPTION 'NF:IIF_NO_VOUCHERS';
  END IF;

  -- every voucher must be real, POSTED, exportable, and in this company
  IF EXISTS (
    SELECT 1 FROM unnest(p_voucher_ids) x(id)
    LEFT JOIN public.nf_vouchers v ON v.id = x.id AND v.company_id = p_company_id
    WHERE v.id IS NULL OR v.status <> 'POSTED' OR NOT v.iif_exportable
  ) THEN
    RAISE EXCEPTION 'NF:IIF_VOUCHER_NOT_EXPORTABLE';
  END IF;

  -- any voucher already exported must appear in p_reexports with a reason
  SELECT array_agg(bv.voucher_id) INTO v_already_exported
    FROM public.nf_iif_batch_vouchers bv
   WHERE bv.voucher_id = ANY(p_voucher_ids);

  IF v_already_exported IS NOT NULL THEN
    FOR v_id IN SELECT unnest(v_already_exported) LOOP
      v_reason := (SELECT r->>'reason' FROM jsonb_array_elements(p_reexports) r WHERE (r->>'voucher_id')::uuid = v_id);
      IF v_reason IS NULL OR btrim(v_reason) = '' THEN
        RAISE EXCEPTION 'NF:IIF_ALREADY_EXPORTED' USING DETAIL = v_id::text;
      END IF;
    END LOOP;
  END IF;

  INSERT INTO public.nf_iif_batches (company_id, created_by, file_name, date_from, date_to, qb_chart_file, qb_chart_checksum)
  VALUES (p_company_id, v_uid, p_file_name, p_from, p_to, p_qb_chart_file, p_qb_chart_checksum)
  RETURNING id INTO v_batch_id;

  INSERT INTO public.nf_iif_batch_vouchers (batch_id, voucher_id, company_id, is_reexport, reason)
  SELECT v_batch_id, x.id, p_company_id,
         x.id = ANY(COALESCE(v_already_exported, ARRAY[]::uuid[])),
         (SELECT r->>'reason' FROM jsonb_array_elements(p_reexports) r WHERE (r->>'voucher_id')::uuid = x.id)
    FROM unnest(p_voucher_ids) x(id);

  RETURN jsonb_build_object('batch_id', v_batch_id, 'voucher_count', array_length(p_voucher_ids, 1));
END
$function$;

REVOKE ALL ON FUNCTION public.nf_iif_record_batch(uuid, text, date, date, text, text, uuid[], jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.nf_iif_record_batch(uuid, text, date, date, text, text, uuid[], jsonb) FROM anon;
GRANT EXECUTE ON FUNCTION public.nf_iif_record_batch(uuid, text, date, date, text, text, uuid[], jsonb) TO authenticated;

COMMIT;
